version: "3"
networks:
  dev:
volumes:
  data:
services:
  web:
    build:
      context: .
      dockerfile: ./docker/dev.Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./app:/app/app
    depends_on:
      - mongo
    restart: on-failure
    networks:
      - dev
  mongo:
    image: mongo:3.6-stretch
    logging:
      driver: none
    ports:
    - "27017:27017"
    volumes:
    - data:/data/db
    networks:
      - dev
  # Comment this to work on localhost
  lt:
    build:
      context: .
      dockerfile: ./docker/lt.Dockerfile
    command: "usr/local/bin/lt --port 3000 -l web -s web-microdev"
    depends_on:
      - web
    restart: on-failure
    networks:
      - dev
