version: "3"
services:
  user:
    build:
      context: .
      dockerfile: ./docker/dev.Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./app:/app/
    depends_on:
      - mongo
  mongo:
    image: mongo:3.6-stretch
    environment:
      - MONGO_DATA_DIR=/data/db
    logging:
      driver: none
    ports:
    - "27017:27017"
    volumes:
    - ./db:/data/db
