version: "3"
services:
  user:
    build:
      context: .
      dockerfile: ./docker-dev.Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./:/app/
    restart: always
    depends_on:
      - postgres
  postgres:
    image: postgres:9.6-alpine
    environment:
      POSTGRES_PASSWORD: postgres
